WINDOW_HEIGHT = 500
WINDOW_WIDTH = 500
BG_COLOR = "#2e2e2e"  # Background color
FG_COLOR = "#ffffff"  # Text color
ENTRY_BG_COLOR = "#404040"  # Entry background color
BUTTON_COLOR = "#555555"
BUTTON_WIDTH = 20


TITLE_FONT = ("Arial", 16)
BUTTON_FONT = ("Arial", 12)

MENU_WINDOW_HEIGHT = 800
MENU_WINDOW_WIDTH = 200
MENU_WINDOW_SIZE = (MENU_WINDOW_WIDTH, MENU_WINDOW_HEIGHT)
APP_POS_X = 700
APP_POS_Y = 300
APP_POS = (APP_POS_X, APP_POS_Y)


MAIN_WINDOW_HEIGHT = 800
MAIN_WINDOW_WIDTH = 1000
MAIN_WINDOW_SIZE = (MAIN_WINDOW_WIDTH, MAIN_WINDOW_HEIGHT)
MAIN_WINDOW_POS = ((APP_POS_X + MENU_WINDOW_WIDTH + 5), APP_POS_Y)
